// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyFavoriteBooksSimple.Data;

namespace MyFavoriteBooksSimple.Migrations
{
    [DbContext(typeof(MyFavoriteBooksContext))]
    [Migration("20201117033840_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("MyFavoriteBooksSimple.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Eric",
                            LastName = "Evans"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Bruno",
                            LastName = "Preiss"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Kenneth",
                            LastName = "Rubin"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Robert",
                            LastName = "Martin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
